FROM samdoshi/haskell-stack
RUN mkdir -p /app/
WORKDIR /app/
COPY app/ /app/
RUN apt update
RUN curl -sL https://deb.nodesource.com/setup_4.x | bash
RUN apt install nodejs
RUN TAR_OPTIONS=--no-same-owner stack setup
RUN stack build

EXPOSE 80

CMD ["/bin/bash"]
