version: '2'
services:
  golang_web_app_image:
    container_name: golang_web_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    container_name: golang_web_app_redis
    image: redis
    ports:
      - "6379:6379"
